from elasticsearch import Elasticsearch
import json

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "EIDVlxEubwqt29bNARhiIihb"

# Found in the 'Manage Deployment' page
CLOUD_ID = "int-Elligent_Chatbot:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDkxY2RlMWY1ODE4NDRiYjU4MWE5ODYzMjI2NzE0N2M0JDIyZTE2YTc2M2U1NDQ3ZjliODgzNmE2MjFmNDYxZTQ5"

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
# print(client.info())

# client.delete(index="newconv", id=1)

# # # loading and indexing data
# with open('data/new_conversation.json') as json_file:
#     data = json.load(json_file)
#     # print(data)

# for i,doc in enumerate(data):
#     resp = client.index(index="newconv", id=i, document=doc)
#     print(resp)

# getting 1 doc
# resp = client.get(index="newconv", id=4)
# print(resp['_source'])

def newconv_es_query(query):
    response = client.search(index='newconv', body={ "query": {
                    "match": {
                        "query": query
                    }
                }})

    answers = []
    for doc in response['hits']['hits']:
        answers.append(doc['_source']['response'])
        break
        
    return answers

